name: build_and_publish

on:
  push:
    branches:
      - '*'
    tags:
      - 'v*'

jobs:
  build-check-and-dry-run-publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - run: npm ci
      - run: npm run build
      - run: npm run check
      - run: npm publish --dry-run
        working-directory: package
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}


  publish-npm:
    needs: build-check-and-dry-run-publish-npm
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - run: npm ci
      - run: npm run build
      - run: npm publish
        working-directory: package
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
